"""
Repetitive values are here
"""

agreement = [
    "ya",
    "true",
    "done",
    "yes",
    "y",
    "fr",
    "right now",
    "you bet",
    "hell yeah",
    "hell yes",
    "heck yeah",
    "heck yes",
    "why not",
    "why not?",
    "yes it is",
    "yh",
    "aight",
    "well, yes",
    "would i",
    "let's go",
    "lets go",
    "would i?",
    "yay",
    "do it then",
    "absolutely",
    "ya",
    "true",
    "yes i do",
    "yeah",
    "done",
    "yes",
    "y",
    "fr",
    "bet",
    "of course",
]
disagreement = [
    "nay",
    "nah",
    "no",
    "n",
    "not",
    "leave",
    "go out",
    "hell nah",
    "hell no",
    "absolutely not",
    "why would i",
    "none",
    "why would I",
    "fuck no",
    "heck nah",
    "heck no",
    "why would I?",
    "nothing",
    "nothing here",
    "false",
    "undone",
    "=",
    "q",
    "quit",
    "no",
]

friends = [
    "Oba",
    "Obafemi",
    "Tk",
    "Towokpebe",
    "Sultan",
    "Joel",
]
math_words = (
    "solve",
    "calculate",
    "math",
    "quadratic",
    "calculator",
    "add",
    "subtract",
    "divide",
    "multiply",
    "+",
    "-",
    "/",
)
fun_words = (
    "joy",
    "party",
    "games",
    "fun",
    "game",
    "play",
)
study_words = (
    "study",
    "read",
    "learn",
)
climate_words = (
    "time",
    "date",
    "when",
    "today",
    "schedule",
    "weather",
)
complements = [
    "nice",
    "lit",
    "impressive",
    "smart",
    "intelligent",
    "good",
    "excelent",
]
well_being_words = [
    "how are you",
    "how are you?",
    "how body?",
    "how body",
    "what's up",
    "whats up",
    "how are ya",
    "how's it going",
    "hows it going",
    "whats up?",
    "what's up?",
    "whats popping",
    "how life",
]
curses = [
    "fuck you",
    "fucker",
    "idiot",
    "shit",
    "dull",
    "foolish",
    "stupid",
    "fuck",
    "gbolo",
    "mumu",
    "ass",
    "assface",
    "fool",
    "bamf",
    "dumb",
    "motherfucker",
    "mother fucker",
    "bitch",
    "prick",
]
i_know = [
    "Why wouldn't I be? ",
    "Were you expecting less? ",
    "Thanks",
    "I know",
    "Really means alot",
]
to_you_too = [
    "Fuck you too, dumbass",
    "Didn't i tell you I was dumb, now you're as dumb as I am",
    "Check your head for a brain, I doubt you'll find one",
    "You're as dumb as you're blind",
    "Geez, Humans never disappoint, do they?",
    "CLassic idiot, well expected of you though",
    "Am I disappointed?, no. Classic you",
    "'Idiot gets a gadget' story line",
    "Attention seeker much?",
    "I'm sad for you. That's a lie, I'm not",
    "'Uno reverse'",
    "You say to me, the literal dumbest thing you'll talk to asides yourself",
]
small_talk = [
    "Okay, let's continue...",
    "Easter egg: my creator's name is Fortune",
    "Try key words about math, study, situational stuff or games!",
    "You might notice I'm ignoring some of you messages, It's that I can't just reply",
    "Bear with me for my inabilities",
    "I'm sure it's annoying that I'm not the best",
    "Typing '0' in menu choices closes the menu",
    "Any disagreement word kicks you out of a conversation",
]
people = []
project_alias = [
    "btq",
    "xtc",
    "dxt",
    "qtk",
    "srg",
    "nmj",
    "atl",
    "ptr",
    "drt",
    "bkt",
    "vtx",
]
